package feeds.tmobile.payment.cql

import com.datastax.gatling.stress.core.BaseFeed
import com.typesafe.scalalogging.LazyLogging

class Payment_transactions_detail_dpt_Feed
  extends BaseFeed with LazyLogging{


  def getPayment_transactions_detail_dpt = {
    def rowData = this.getRowData


    Iterator.continually(rowData)
  }

  def getRowData = {

    val bigint_size = 12

    Map(
      "dps_payment_id" -> getRandomNumber(bigint_size).toString,
      "card_first_6" -> getRandomNumber(bigint_size).toString,
      "card_last_4" -> getRandomNumber(bigint_size).toString,
      "process_id" -> getRandomNumber(bigint_size).toString,
      "accuity_abarouting_number" -> getRandomNumber(bigint_size).toString,
      "acquirer_approval_code" -> getRandomNumber(bigint_size).toString,
      "acquirer_avs_responsecode" -> getRandomNumber(bigint_size).toString,
      "acquirer_cvv_responsecode" -> getRandomNumber(bigint_size).toString,
      "acquirer_name" -> getRandomNumber(bigint_size).toString,
      "acquirer_parent_payment_id" -> getRandomNumber(bigint_size).toString,
      "acquirer_payment_id" -> getRandomNumber(bigint_size).toString,
      "address_matched" -> getRandomNumber(bigint_size).toString,
      "address_type" -> getRandomNumber(bigint_size).toString,
      "amount" -> getRandomNumber(bigint_size).toString,
      "application_id" -> getRandomNumber(bigint_size).toString,
      "application_name" -> getRandomNumber(bigint_size).toString,
      "application_version" -> getRandomNumber(bigint_size).toString,
      "applicationcryptogram" -> getRandomNumber(bigint_size).toString,
      "auth_hold_revrsal_action" -> getRandomNumber(bigint_size).toString,
      "authorized_amount" -> getRandomNumber(bigint_size).toString,
      "bank_name" -> getRandomNumber(bigint_size).toString,
      "batch_id" -> getRandomNumber(bigint_size).toString,
      "bill_due_date" -> getCurrentTimestamp,
      "biller_code" -> getRandomNumber(bigint_size).toString,
      "billing_account_number" -> getRandomNumber(bigint_size).toString,
      "business_segment" -> getRandomNumber(bigint_size).toString,
      "business_unit" -> getRandomNumber(bigint_size).toString,
      "card_brand" -> getRandomNumber(bigint_size).toString,
      "card_present" -> getRandomNumber(bigint_size).toString,
      "cardholder_address_line1" -> getRandomNumber(bigint_size).toString,
      "cardholder_address_line2" -> getRandomNumber(bigint_size).toString,
      "cardholder_address_line3" -> getRandomNumber(bigint_size).toString,
      "cardholder_address_line4" -> getRandomNumber(bigint_size).toString,
      "cardholder_address_line5" -> getRandomNumber(bigint_size).toString,
      "cardholder_city" -> getRandomNumber(bigint_size).toString,
      "cardholder_state" -> getRandomNumber(bigint_size).toString,
      "cardholder_zip" -> getRandomNumber(bigint_size).toString,
      "channel_id" -> getRandomNumber(bigint_size).toString,
      "charge_source" -> getRandomNumber(bigint_size).toString,
      "chargeback_export_destination" -> getRandomNumber(bigint_size).toString,
      "chargeback_export_status" -> getRandomNumber(bigint_size).toString,
      "client_id" -> getRandomNumber(bigint_size).toString,
      "common_customer_id" -> getRandomNumber(bigint_size).toString,
      "contactless_category" -> getRandomNumber(bigint_size).toString,
      "created_by" -> getRandomNumber(bigint_size).toString,
      "created_date" -> getCurrentTimestamp,
      "customer_mobile_phone" -> getRandomNumber(bigint_size).toString,
      "customer_name" -> getRandomNumber(bigint_size).toString,
      "customer_present" -> getRandomNumber(bigint_size).toString,
      "debit_signature_code" -> getRandomNumber(bigint_size).toString,
      "deviceid" -> getRandomNumber(bigint_size).toString,
      "dps_response_code" -> getRandomNumber(bigint_size).toString,
      "dps_response_message" -> getRandomNumber(bigint_size).toString,
      "dps_shortcode" -> getRandomNumber(bigint_size).toString,
      "electronic_authentication_capability" -> getRandomNumber(bigint_size).toString,
      "entrymode" -> getRandomNumber(bigint_size).toString,
      "expiration_date" -> getRandomNumber(bigint_size).toString,
      "fraud_check_transaction_id" -> getRandomNumber(bigint_size).toString,
      "fraud_decision_status" -> getRandomNumber(bigint_size).toString,
      "guid" -> getRandomNumber(bigint_size).toString,
      "import_batch_id" -> getRandomNumber(bigint_size).toString,
      "integratedchipdata" -> getRandomNumber(bigint_size).toString,
      "keyed_or_manual_indicator" -> getRandomNumber(bigint_size).toString,
      "legacytoken" -> getRandomNumber(bigint_size).toString,
      "local_transaction_time" -> getCurrentTimestamp,
      "mac_address" -> getRandomNumber(bigint_size).toString,
      "manager_login_id" -> getRandomNumber(bigint_size).toString,
      "merchant_routing_id" -> getRandomNumber(bigint_size).toString,
      "modified_by" -> getRandomNumber(bigint_size).toString,
      "modified_date" -> getCurrentTimestamp,
      "onlineoffline_indicator" -> getRandomNumber(bigint_size).toString,
      "operation_type" -> getRandomNumber(bigint_size).toString,
      "operator_id" -> getRandomNumber(bigint_size).toString,
      "order_number" -> getRandomNumber(bigint_size).toString,
      "order_type" -> getRandomNumber(bigint_size).toString,
      "parent_order_id" -> getRandomNumber(bigint_size).toString,
      "parent_payment_id" -> getRandomNumber(bigint_size).toString,
      "payment_instrument_account_number" -> getRandomNumber(bigint_size).toString,
      "payment_instrument_category" -> getRandomNumber(bigint_size).toString,
      "payment_instrument_holder_firstname" -> getRandomNumber(bigint_size).toString,
      "payment_instrument_holder_fullname" -> getRandomNumber(bigint_size).toString,
      "payment_instrument_holder_lastname" -> getRandomNumber(bigint_size).toString,
      "payment_instrument_holder_phonenumber" -> getRandomNumber(bigint_size).toString,
      "payment_method_code" -> getRandomNumber(bigint_size).toString,
      "payment_type_code" -> getRandomNumber(bigint_size).toString,
      "pin_indicator" -> getRandomNumber(bigint_size).toString,
      "pinless_indicator" -> getRandomNumber(bigint_size).toString,
      "posting_destination" -> getRandomNumber(bigint_size).toString,
      "posting_status" -> getRandomNumber(bigint_size).toString,
      "prepaid_available_balance" -> getRandomNumber(bigint_size).toString,
      "prepaid_card_indicator" -> getRandomNumber(bigint_size).toString,
      "product_group" -> getRandomNumber(bigint_size).toString,
      "program_code" -> getRandomNumber(bigint_size).toString,
      "refunded_amount" -> getRandomNumber(bigint_size).toString,
      "remaining_balance" -> getRandomNumber(bigint_size).toString,
      "reversal_action" -> getRandomNumber(bigint_size).toString,
      "routing_number" -> getRandomNumber(bigint_size).toString,
      "sale_terminal_num" -> getRandomNumber(bigint_size).toString,
      "settlement_batch_id" -> getRandomNumber(bigint_size).toString,
      "settlement_required" -> getRandomNumber(bigint_size).toString,
      "settlement_status" -> getRandomNumber(bigint_size).toString,
      "ship_to_address_line1" -> getRandomNumber(bigint_size).toString,
      "ship_to_address_line2" -> getRandomNumber(bigint_size).toString,
      "ship_to_address_line3" -> getRandomNumber(bigint_size).toString,
      "ship_to_address_line4" -> getRandomNumber(bigint_size).toString,
      "ship_to_address_line5" -> getRandomNumber(bigint_size).toString,
      "ship_to_city" -> getRandomNumber(bigint_size).toString,
      "ship_to_state" -> getRandomNumber(bigint_size).toString,
      "ship_to_zip" -> getRandomNumber(bigint_size).toString,
      "status" -> getRandomNumber(bigint_size).toString,
      "status_modified_date" -> getCurrentTimestamp,
      "store_addressline_1" -> getRandomNumber(bigint_size).toString,
      "store_addressline_2" -> getRandomNumber(bigint_size).toString,
      "store_cityname" -> getRandomNumber(bigint_size).toString,
      "store_countrycode" -> getRandomNumber(bigint_size).toString,
      "store_id" -> getRandomNumber(bigint_size).toString,
      "store_statecode" -> getRandomNumber(bigint_size).toString,
      "store_zip" -> getRandomNumber(bigint_size).toString,
      "stored_payment_indicator" -> getRandomNumber(bigint_size).toString,
      "surcharge_amount" -> getRandomNumber(bigint_size).toString,
      "tax_amount" -> getRandomNumber(bigint_size).toString,
      "terminal_make" -> getRandomNumber(bigint_size).toString,
      "terminal_model" -> getRandomNumber(bigint_size).toString,
      "terminalcapability" -> getRandomNumber(bigint_size).toString,
      "terminalid" -> getRandomNumber(bigint_size).toString,
      "terminaltype" -> getRandomNumber(bigint_size).toString,
      "termscond_accepted" -> getRandomNumber(bigint_size).toString,
      "termscond_accepted_timestamp" -> getCurrentTimestamp,
      "termscond_application_id" -> getRandomNumber(bigint_size).toString,
      "timeout_reversal" -> getRandomNumber(bigint_size).toString,
      "tmoaccountholder_address_line1" -> getRandomNumber(bigint_size).toString,
      "tmoaccountholder_address_line2" -> getRandomNumber(bigint_size).toString,
      "tmoaccountholder_address_line3" -> getRandomNumber(bigint_size).toString,
      "tmoaccountholder_address_line4" -> getRandomNumber(bigint_size).toString,
      "tmoaccountholder_address_line5" -> getRandomNumber(bigint_size).toString,
      "tmoaccountholder_city" -> getRandomNumber(bigint_size).toString,
      "tmoaccountholder_state" -> getRandomNumber(bigint_size).toString,
      "tmoaccountholder_zip" -> getRandomNumber(bigint_size).toString,
      "tmotoken" -> getRandomNumber(bigint_size).toString,
      "trackonedata" -> getRandomNumber(bigint_size).toString,
      "tracktwodata" -> getRandomNumber(bigint_size).toString,
      "transaction_date" -> getCurrentTimestamp,
      "transaction_type" -> getRandomNumber(bigint_size).toString,
      "verification_method" -> getRandomNumber(bigint_size).toString,
      "void_reason" -> getRandomNumber(bigint_size).toString,
      "zip_matched" -> getRandomNumber(bigint_size).toString
    )
  }

  def getRandomNumber(digits:Int) = {
    System.nanoTime()
  }
}
