package actions.tmobile.payment.solr

import com.datastax.driver.core.querybuilder.QueryBuilder._
import com.datastax.driver.core.querybuilder.{Insert, QueryBuilder}
import com.datastax.gatling.plugin.CqlPredef._
import com.datastax.gatling.plugin.DsePredef.cql
import com.datastax.gatling.stress.core.BaseAction
import com.datastax.gatling.stress.libs.{Cassandra, SimConfig}
import io.gatling.core.Predef._
import io.gatling.core.structure.ChainBuilder


class SearchWriteActions(cassandra: Cassandra, simConf: SimConfig) extends BaseAction(cassandra, simConf) {

  private val writeDptQuery: Insert = QueryBuilder.insertInto(keyspace, table)
    .value("dps_payment_id", raw(":dps_payment_id"))
    .value("card_first_6", raw(":card_first_6"))
    .value("card_last_4", raw(":card_last_4"))
    .value("process_id", raw(":process_id"))
    .value("accuity_abarouting_number", raw(":accuity_abarouting_number"))
    .value("acquirer_approval_code", raw(":acquirer_approval_code"))
    .value("acquirer_avs_responsecode", raw(":acquirer_avs_responsecode"))
    .value("acquirer_cvv_responsecode", raw(":acquirer_cvv_responsecode"))
    .value("acquirer_name", raw(":acquirer_name"))
    .value("acquirer_parent_payment_id", raw(":acquirer_parent_payment_id"))
    .value("acquirer_payment_id", raw(":acquirer_payment_id"))
    .value("address_matched", raw(":address_matched"))
    .value("address_type", raw(":address_type"))
    .value("amount", raw(":amount"))
    .value("application_id", raw(":application_id"))
    .value("application_name", raw(":application_name"))
    .value("application_version", raw(":application_version"))
    .value("applicationcryptogram", raw(":applicationcryptogram"))
    .value("auth_hold_revrsal_action", raw(":auth_hold_revrsal_action"))
    .value("authorized_amount", raw(":authorized_amount"))
    .value("bank_name", raw(":bank_name"))
    .value("batch_id", raw(":batch_id"))
    .value("bill_due_date", raw(":bill_due_date"))
    .value("biller_code", raw(":biller_code"))
    .value("billing_account_number", raw(":billing_account_number"))
    .value("business_segment", raw(":business_segment"))
    .value("business_unit", raw(":business_unit"))
    .value("card_brand", raw(":card_brand"))
    .value("card_present", raw(":card_present"))
    .value("cardholder_address_line1", raw(":cardholder_address_line1"))
    .value("cardholder_address_line2", raw(":cardholder_address_line2"))
    .value("cardholder_address_line3", raw(":cardholder_address_line3"))
    .value("cardholder_address_line4", raw(":cardholder_address_line4"))
    .value("cardholder_address_line5", raw(":cardholder_address_line5"))
    .value("cardholder_city", raw(":cardholder_city"))
    .value("cardholder_state", raw(":cardholder_state"))
    .value("cardholder_zip", raw(":cardholder_zip"))
    .value("charge_source", raw(":charge_source"))
    .value("chargeback_export_destination", raw(":chargeback_export_destination"))
    .value("chargeback_export_status", raw(":chargeback_export_status"))
    .value("client_id", raw(":client_id"))
    .value("common_customer_id", raw(":common_customer_id"))
    .value("contactless_category", raw(":contactless_category"))
    .value("created_by", raw(":created_by"))
    .value("created_date", raw(":created_date"))
    .value("customer_mobile_phone", raw(":customer_mobile_phone"))
    .value("customer_name", raw(":customer_name"))
    .value("customer_present", raw(":customer_present"))
    .value("debit_signature_code", raw(":debit_signature_code"))
    .value("deviceid", raw(":deviceid"))
    .value("dps_response_code", raw(":dps_response_code"))
    .value("dps_response_message", raw(":dps_response_message"))
    .value("dps_shortcode", raw(":dps_shortcode"))
    .value("electronic_authentication_capability", raw(":electronic_authentication_capability"))
    .value("entrymode", raw(":entrymode"))
    .value("expiration_date", raw(":expiration_date"))
    .value("fraud_check_transaction_id", raw(":fraud_check_transaction_id"))
    .value("fraud_decision_status", raw(":fraud_decision_status"))
    .value("guid", raw(":guid"))
    .value("import_batch_id", raw(":import_batch_id"))
    .value("integratedchipdata", raw(":integratedchipdata"))
    .value("keyed_or_manual_indicator", raw(":keyed_or_manual_indicator"))
    .value("legacytoken", raw(":legacytoken"))
    .value("local_transaction_time", raw(":local_transaction_time"))
    .value("mac_address", raw(":mac_address"))
    .value("manager_login_id", raw(":manager_login_id"))
    .value("member_id", raw(":member_id"))
    .value("member_id_type", raw(":member_id_type"))
    .value("merchant_routing_id", raw(":merchant_routing_id"))
    .value("modified_by", raw(":modified_by"))
    .value("modified_date", raw(":modified_date"))
    .value("onlineoffline_indicator", raw(":onlineoffline_indicator"))
    .value("operation_type", raw(":operation_type"))
    .value("operator_id", raw(":operator_id"))
    .value("order_number", raw(":order_number"))
    .value("order_type", raw(":order_type"))
    .value("parent_order_id", raw(":parent_order_id"))
    .value("parent_payment_id", raw(":parent_payment_id"))
    .value("partner_id", raw(":partner_id"))
    .value("payment_instrument_account_number", raw(":payment_instrument_account_number"))
    .value("payment_instrument_category", raw(":payment_instrument_category"))
    .value("payment_instrument_holder_firstname", raw(":payment_instrument_holder_firstname"))
    .value("payment_instrument_holder_fullname", raw(":payment_instrument_holder_fullname"))
    .value("payment_instrument_holder_lastname", raw(":payment_instrument_holder_lastname"))
    .value("payment_instrument_holder_phonenumber", raw(":payment_instrument_holder_phonenumber"))
    .value("payment_method_code", raw(":payment_method_code"))
    .value("payment_type_code", raw(":payment_type_code"))
    .value("pin_indicator", raw(":pin_indicator"))
    .value("pinless_indicator", raw(":pinless_indicator"))
    .value("posting_destination", raw(":posting_destination"))
    .value("posting_status", raw(":posting_status"))
    .value("prepaid_available_balance", raw(":prepaid_available_balance"))
    .value("prepaid_card_indicator", raw(":prepaid_card_indicator"))
    .value("product_group", raw(":product_group"))
    .value("program_code", raw(":program_code"))
    .value("refunded_amount", raw(":refunded_amount"))
    .value("remaining_balance", raw(":remaining_balance"))
    .value("reversal_action", raw(":reversal_action"))
    .value("routing_number", raw(":routing_number"))
    .value("sale_terminal_num", raw(":sale_terminal_num"))
    .value("settlement_batch_id", raw(":settlement_batch_id"))
    .value("settlement_required", raw(":settlement_required"))
    .value("settlement_status", raw(":settlement_status"))
    .value("ship_to_address_line1", raw(":ship_to_address_line1"))
    .value("ship_to_address_line2", raw(":ship_to_address_line2"))
    .value("ship_to_address_line3", raw(":ship_to_address_line3"))
    .value("ship_to_address_line4", raw(":ship_to_address_line4"))
    .value("ship_to_address_line5", raw(":ship_to_address_line5"))
    .value("ship_to_city", raw(":ship_to_city"))
    .value("ship_to_state", raw(":ship_to_state"))
    .value("ship_to_zip", raw(":ship_to_zip"))
    .value("status", raw(":status"))
    .value("status_modified_date", raw(":status_modified_date"))
    .value("store_addressline_1", raw(":store_addressline_1"))
    .value("store_addressline_2", raw(":store_addressline_2"))
    .value("store_cityname", raw(":store_cityname"))
    .value("store_countrycode", raw(":store_countrycode"))
    .value("store_id", raw(":store_id"))
    .value("store_statecode", raw(":store_statecode"))
    .value("store_zip", raw(":store_zip"))
    .value("stored_payment_indicator", raw(":stored_payment_indicator"))
    .value("surcharge_amount", raw(":surcharge_amount"))
    .value("tax_amount", raw(":tax_amount"))
    .value("terminal_make", raw(":terminal_make"))
    .value("terminal_model", raw(":terminal_model"))
    .value("terminalcapability", raw(":terminalcapability"))
    .value("terminalid", raw(":terminalid"))
    .value("terminaltype", raw(":terminaltype"))
    .value("termscond_accepted", raw(":termscond_accepted"))
    .value("termscond_accepted_timestamp", raw(":termscond_accepted_timestamp"))
    .value("termscond_application_id", raw(":termscond_application_id"))
    .value("timeout_reversal", raw(":timeout_reversal"))
    .value("tmoaccountholder_address_line1", raw(":tmoaccountholder_address_line1"))
    .value("tmoaccountholder_address_line2", raw(":tmoaccountholder_address_line2"))
    .value("tmoaccountholder_address_line3", raw(":tmoaccountholder_address_line3"))
    .value("tmoaccountholder_address_line4", raw(":tmoaccountholder_address_line4"))
    .value("tmoaccountholder_address_line5", raw(":tmoaccountholder_address_line5"))
    .value("tmoaccountholder_city", raw(":tmoaccountholder_city"))
    .value("tmoaccountholder_state", raw(":tmoaccountholder_state"))
    .value("tmoaccountholder_zip", raw(":tmoaccountholder_zip"))
    .value("tmotoken", raw(":tmotoken"))
    .value("trackonedata", raw(":trackonedata"))
    .value("tracktwodata", raw(":tracktwodata"))
    .value("transaction_date", raw(":transaction_date"))
    .value("transaction_type", raw(":transaction_type"))
    .value("verification_method", raw(":verification_method"))
    .value("void_reason", raw(":void_reason"))
    .value("wallet_id", raw(":wallet_id"))
    .value("zip_matched", raw(":zip_matched"))

  private val writeDptPreparedStatement = session.prepare(writeDptQuery)

  def writeDpt(name:String): ChainBuilder = {

    exec(
      cql(name)
        .executeNamed(writeDptPreparedStatement)
    )

  }



}
